AWSTemplateFormatVersion: 2010-09-09
Description: Creates an ECR repository with a lifecycle policy for repository images.
Parameters:
  Owner:
    Type: String
    Description: >-
      Individual or team who created the resource. 
      Must be lower case, as it is used as part of the repository name. 

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${Owner}/repo-with-lifecycle
      LifecyclePolicy:
        # For any tag value, keep the last countNumber value of images.
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Only keep 10 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
              },
              "action": { "type": "expire" }
            }]
          }
      Tags:
        - Key: Owner
          Value: !Ref Owner